import { createFileRoute, Link } from "@tanstack/react-router";
import { Scale } from "lucide-react";

export const Route = createFileRoute("/terms")({
  component: TermsPage,
  head: () => ({
    meta: [
      { title: "Terms of Service — Paralegal AI" },
      { name: "description", content: "Terms of Service for Paralegal AI." },
      { property: "og:title", content: "Terms of Service — Paralegal AI" },
      { property: "og:url", content: "/terms" },
      { name: "robots", content: "noindex,follow" },
    ],
    links: [{ rel: "canonical", href: "/terms" }],
  }),
});

function TermsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-background to-secondary flex flex-col">
      <header className="px-6 py-5 flex items-center justify-between max-w-6xl mx-auto w-full">
        <Link to="/" className="flex items-center gap-2 font-bold text-primary">
          <Scale className="h-6 w-6" />
          Paralegal AI
        </Link>
        <Link to="/auth" className="text-sm font-medium text-primary hover:text-accent">
          Sign in
        </Link>
      </header>

      <main className="flex-1 max-w-3xl mx-auto px-6 py-16 w-full">
        <h1 className="text-4xl font-bold text-primary mb-2">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-10">Last updated: May 2026</p>

        <div className="prose prose-sm max-w-none text-foreground space-y-8">
          <section>
            <h2 className="text-xl font-semibold text-primary mb-3">1. Acceptance of Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              By accessing or using Paralegal AI ("the Service"), you agree to be bound by these Terms of
              Service. If you do not agree to these terms, please do not use the Service. These terms apply
              to all users, including legal practitioners, law firms, and any other individuals or
              organisations using the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-primary mb-3">2. Description of Service</h2>
            <p className="text-muted-foreground leading-relaxed">
              Paralegal AI is an AI-powered case management platform designed to assist legal aid
              practitioners with case logging, report generation, and document preparation. The Service is
              a productivity tool and does not constitute legal advice. All outputs generated by the AI
              should be reviewed by a qualified legal professional before use.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-primary mb-3">3. User Responsibilities</h2>
            <p className="text-muted-foreground leading-relaxed mb-3">You agree to:</p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2 leading-relaxed">
              <li>Provide accurate information when creating your account.</li>
              <li>Keep your login credentials confidential and notify us of any unauthorised access.</li>
              <li>Use the Service in compliance with all applicable laws and professional regulations.</li>
              <li>Not upload any data that you do not have the right to process or share.</li>
              <li>Not use the Service to generate content that is misleading, fraudulent, or unlawful.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-primary mb-3">4. Client Data and Confidentiality</h2>
            <p className="text-muted-foreground leading-relaxed">
              You are solely responsible for ensuring that any client data you enter into the Service
              complies with your professional confidentiality obligations and applicable data protection
              laws. Paralegal AI processes data on your behalf and does not sell or share your client data
              with third parties except as necessary to provide the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-primary mb-3">5. AI-Generated Content</h2>
            <p className="text-muted-foreground leading-relaxed">
              The Service uses artificial intelligence to assist with drafting reports and documents.
              AI-generated content may contain errors, omissions, or inaccuracies. You acknowledge that
              all AI outputs must be reviewed and verified by a qualified professional before submission
              to any court, regulatory body, or third party. Paralegal AI accepts no liability for
              decisions made on the basis of AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-primary mb-3">6. Intellectual Property</h2>
            <p className="text-muted-foreground leading-relaxed">
              The Service, including its design, code, and underlying technology, is owned by Paralegal AI
              and protected by applicable intellectual property laws. You retain ownership of all data and
              content you upload. You grant Paralegal AI a limited licence to process your content solely
              for the purpose of providing the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-primary mb-3">7. Limitation of Liability</h2>
            <p className="text-muted-foreground leading-relaxed">
              To the maximum extent permitted by law, Paralegal AI shall not be liable for any indirect,
              incidental, special, or consequential damages arising out of or in connection with your use
              of the Service. Our total liability shall not exceed the amount paid by you for the Service
              in the twelve months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-primary mb-3">8. Termination</h2>
            <p className="text-muted-foreground leading-relaxed">
              We reserve the right to suspend or terminate your access to the Service at any time if you
              violate these Terms or engage in conduct that we determine to be harmful to the Service or
              other users. You may close your account at any time by contacting us.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-primary mb-3">9. Changes to These Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              We may update these Terms from time to time. We will notify you of significant changes via
              email or an in-app notice. Continued use of the Service after changes take effect constitutes
              your acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-primary mb-3">10. Contact</h2>
            <p className="text-muted-foreground leading-relaxed">
              If you have any questions about these Terms, please contact us at{" "}
              <a href="mailto:admin@domusdeiug.com" className="text-accent hover:underline">
                admin@domusdeiug.com
              </a>.
            </p>
          </section>
        </div>
      </main>

      <footer className="border-t border-border py-6 px-6">
        <div className="max-w-6xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-3 text-xs text-muted-foreground">
          <span>© {new Date().getFullYear()} Domus Dei Uganda. All rights reserved.</span>
          <div className="flex gap-4">
            <Link to="/terms" className="hover:text-primary transition-colors">Terms of Service</Link>
            <Link to="/privacy" className="hover:text-primary transition-colors">Privacy Policy</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
